export default {
 // app
  APP_START: "APP_START",
  APP_ERROR: "APP_START",
  APP_SUCCESS: "APP_SUCCESS",
  APP_FINISH: "APP_FINISH",

  CHANGE_ACTIVE_SLIDE: "CHANGE_ACTIVE_SLIDE",

  SHOW_MODAL: "SHOW_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",

  CHANGE_PROFILE: "CHANGE_PROFILE",

  CHECK_NETWORK_START: "CHECK_NETWORK_LOADING_START",
  CHECK_NETWORK_SUCCESS: "CHECK_NETWORK_SUCCESS",
  CHECK_NETWORK_ERROR: "CHECK_NETWORK_ERROR",
  CHECK_NETWORK_FINISH: "CHECK_NETWORK_FINISH",
  CHANGE_NETWORK_CONFIG: "CHANGE_NETWORK_CONFIG",
};
