export default {
  // wallet slider
  CHANGE_ACTIVE_SLIDE: "CHANGE_ACTIVE_SLIDE",

  // profile
  CHANGE_PROFILE: "CHANGE_PROFILE",

  // server
  CHECK_NETWORK_START: "CHECK_NETWORK_LOADING_START",
  CHECK_NETWORK_SUCCESS: "CHECK_NETWORK_SUCCESS",
  CHECK_NETWORK_ERROR: "CHECK_NETWORK_ERROR",
  CHECK_NETWORK_FINISH: "CHECK_NETWORK_FINISH",
  CHANGE_NETWORK_CONFIG: "CHANGE_NETWORK_CONFIG",
};
