export const SCREEN_NAMES =  {
  // navigators
  APP_NAVIGATOR: "APP_NAVIGATOR",
  ADD_WALLET_NAVIGATOR: "ADD_WALLET_NAVIGATOR",
  TABS_NAVIGATOR: "TABS_NAVIGATOR",

  // screens
  APP_LOADING_SCREEN: "APP_LOADING_SCREEN",
  MODAL_SCREEN: "MODAL_SCREEN",
  QR_SCANNER_SCREEN: "QR_SCANNER_SCREEN",

  // auth
  LOCAL_AUTH_SCREEN: "LOCAL_AUTH_SCREEN",

  // wallet creating
  ADD_WALLET_SCREEN: "ADD_WALLET_SCREEN",
  GENERATE_WALLET_SCREEN: "GENERATE_WALLET_SCREEN",
  IMPORT_WALLET_SCREEN: "IMPORT_WALLET_SCREEN",

  // wallet
  DETAILS_SCREEN: "DETAILS_SCREEN",
  WALLET_SCREEN: "WALLET_SCREEN",
  SEND_SETUP_SCREEN: "SEND_SETUP_SCREEN",
  SEND_CONFIRM_SCREEN: "SEND_CONFIRM_SCREEN",
  RECEIVE_SCREEN: "RECEIVE_SCREEN",

  //
  EXCHANGE_SCREEN: "EXCHANGE_SCREEN",
  ANALYTICS_SCREEN: "ANALYTICS_SCREEN",

  // settings
  SETTINGS_WALLET_LIST: "SETTINGS_WALLET_LIST",
  SETTINGS_WALLET_ITEM: "SETTINGS_WALLET_ITEM",
  SETTINGS_WALLET_PUBLIC_KEY: "SETTINGS_WALLET_PUBLIC_KEY",
  SETTINGS_WALLET_PRIVATE_KEY: "SETTINGS_WALLET_PRIVATE_KEY",
  GLOBAL_SETTINGS_SCREEN: "GLOBAL_SETTINGS_SCREEN",
  SECURITY_SETTINGS_SCREEN: "SECURITY_SETTINGS_SCREEN",
  SERVER_SETTINGS_SCREEN: "SERVER_SETTINGS_SCREEN",
  NETWORK_URL_ERROR_SCREEN: "NETWORK_URL_ERROR_SCREEN",
};

export const SECURE_STORE_NAMES = {
  WALLETS: "WALLETS",
  ACTIVE_WALLET_ADDRESS: "ACTIVE_WALLET_ADDRESS",
  GRAPH_NETWORK_URL: "GRAPH_NETWORK_URL",
  PROFILE: "PROFILE",
};

export const DEFAULT_RESOURCES = {
  graphCoinSvgUri: "https://glcdn.sgp1.digitaloceanspaces.com/graph/coin.svg",
  graphCoinPngUri: "https://glcdn.sgp1.digitaloceanspaces.com/graph/coin.png",
  graphNetworkUrl: "https://core.graph.finance",
};

export const MONTHS_LIST = [
  "Января",
  "Февраля",
  "Марта",
  "Апреля",
  "Мая",
  "Июня",
  "Июля",
  "Августа",
  "Сентября",
  "Октября",
  "Ноября",
  "Декабря",
];

export const TRANSACTION_STATUS = {
  CONFIRMED: "ПОДТВЕРЖДЕНО",
  UNCONFIRMED: "НЕПОДТВЕРЖДЕНО"
};
