export const SCREEN_NAMES =  {
  // navigators
  APP_NAVIGATOR: "APP_NAVIGATOR",
  AUTHORIZATION_NAVIGATOR: "AUTHORIZATION_NAVIGATOR",
  TABS_NAVIGATOR: "TABS_NAVIGATOR",

  // screens
  APP_LOADING_SCREEN: "APP_LOADING_SCREEN",
  MODAL_SCREEN: "MODAL_SCREEN",
  AUTH_START_SCREEN: "AUTH_START_SCREEN",
  GENERATE_WALLET_SCREEN: "GENERATE_WALLET_SCREEN",
  IMPORT_WALLET_SCREEN: "IMPORT_WALLET_SCREEN",
  DETAILS_SCREEN: "DETAILS_SCREEN",
  WALLET_SCREEN: "WALLET_SCREEN",
  EXCHANGE_SCREEN: "EXCHANGE_SCREEN",
  ANALYTICS_SCREEN: "ANALYTICS_SCREEN",
  SETTINGS_SCREEN: "SETTINGS_SCREEN",
  SETTINGS_WALLET_LIST: "SETTINGS_WALLET_LIST",
  SETTINGS_WALLET_ITEM: "SETTINGS_WALLET_ITEM",
  GLOBAL_SETTINGS_SCREEN: "GLOBAL_SETTINGS_SCREEN",
  SECURITY_SETTINGS_SCREEN: "SECURITY_SETTINGS_SCREEN",
  SERVER_SETTINGS_SCREEN: "SERVER_SETTINGS_SCREEN",
  NETWORK_URL_ERROR_SCREEN: "NETWORK_URL_ERROR_SCREEN",
};

export const SECURE_STORE_NAMES = {
  WALLETS: "WALLETS",
  ACTIVE_WALLET_ADDRESS: "ACTIVE_WALLET_ADDRESS",
  GRAPH_NETWORK_URL: "GRAPH_NETWORK_URL",
  PROFILE: "PROFILE",
};

export const DEFAULT_RESOURCES = {
  graphCoinSvgUri: "https://glcdn.sgp1.digitaloceanspaces.com/graph/coin.svg",
  graphNetworkUrl: "https://core.graph.finance",
};
