export const SCREEN_NAMES =  {
  // navigators
  APP_NAVIGATOR: "APP_NAVIGATOR",
  AUTHORIZATION_NAVIGATOR: "AUTHORIZATION_NAVIGATOR",
  TABS_NAVIGATOR: "TABS_NAVIGATOR",

  // screens
  MODAL_SCREEN: "MODAL_SCREEN",
  AUTH_START_SCREEN: "AUTH_START_SCREEN",
  GENERATE_WALLET_SCREEN: "GENERATE_WALLET_SCREEN",
  IMPORT_WALLET_SCREEN: "IMPORT_WALLET_SCREEN",
  DETAILS_SCREEN: "DETAILS_SCREEN",
  WALLET_SCREEN: "WALLET_SCREEN",
  EXCHANGE_SCREEN: "EXCHANGE_SCREEN",
  ANALYTICS_SCREEN: "ANALYTICS_SCREEN",
  SETTINGS_SCREEN: "SETTINGS_SCREEN",
};

export const SECURE_STORE_NAMES = {
  WALLET: "WALLET",
};
