export default {
  WALLET_LOAD_START: "WALLET_LOAD_START",
  WALLET_LIST_LOAD_SUCCESS: "WALLET_LIST_LOAD_SUCCESS",
  WALLET_LOAD_ERROR: "WALLET_LOAD_ERROR",
  WALLET_LOAD_FINISH: "WALLET_LOAD_FINISH",
  WALLET_SET_ACTIVE: "WALLET_SET_ACTIVE",
  WALLET_CHANGE_NAME: "WALLET_CHANGE_NAME",

  CHANGE_AUTHENTICATED: "CHANGE_AUTHENTICATED",
};
