export default {
  WALLET_LOAD_START: "WALLET_LOAD_START",
  WALLET_LOAD_SUCCESS: "WALLET_LOAD_SUCCESS",
  WALLET_LOAD_ERROR: "WALLET_LOAD_ERROR",
  WALLET_LOAD_FINISH: "WALLET_LOAD_FINISH",

  CHANGE_AUTHENTICATED: "CHANGE_AUTHENTICATED",
};
