export default {
  GENERATE_START: "GENERATE_START",
  GENERATE_SUCCESS: "GENERATE_SUCCESS",
  GENERATE_ERROR: "GENERATE_ERROR",
  GENERATE_FINISH: "GENERATE_FINISH",

  IMPORT_START: "IMPORT_START",
  IMPORT_SUCCESS: "IMPORT_SUCCESS",
  IMPORT_ERROR: "IMPORT_ERROR",
  IMPORT_FINISH: "IMPORT_FINISH",

  CHANGE_AUTHENTICATED: "CHANGE_AUTHENTICATED",
};
